const petClinicRules = {
  CLINIC_WORKING_HOURS : [9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
  CLINIC_TIME_ZONE_OFFSET : 3,
  CLINIC_APPOINTMENT_GAP: 1,
  MAX_ACTIVE_APPOINTMENTS: 3,
  MAX_APPOINTMENTS_PER_DAY: 3,
  MAX_PETS_PER_USER: 3

}
 
export  default petClinicRules