const petClinicRules = {
  CLINIC_WORKING_HOURS : [6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
  CLINIC_TIME_ZONE_OFFSET : 3,
  CLINIC_APPOINTMENT_GAP: 1,
  MAX_ACTIVE_APPOINTMENTS: 3,
  MAX_APPOINTMENTS_PER_DAY: 1,
  MAX_SHELTER_CAPACITY: 40
  // 4 pets
  // MAX_PETS_PER_USER: 4
  

}
 
export  default petClinicRules